[package]
name = "egui-enum-plot"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = {version = "0.32"}
egui_plot = "0.33"


[features]
debug_impl = []
fancier_float_formatting = []

[dev-dependencies]
eframe = "0.32"
