[package]
name = "egui-enum-plot"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = {version = "0.27"}
egui_plot = "0.27"


[features]
debug_impl = []
fancier_float_formatting = []

[dev-dependencies]
eframe = "0.27"
